Fully automatic resealing
If unsealing fails, and the user chooses to continue the boot process
anyway (so we know they still trust their system), make AEM pass that
information and the SRK password across the initrd barrier using the
tmpfs file /run/antievilmaid_seal, which will trigger the rootfs
systemd antievilmaid_seal.service.

Also remove deprecated or redundant sections from the README.

diff --git a/anti-evil-maid/90anti-evil-maid/anti-evil-maid-unseal b/anti-evil-maid/90anti-evil-maid/anti-evil-maid-unseal
--- a/anti-evil-maid/90anti-evil-maid/anti-evil-maid-unseal
+++ b/anti-evil-maid/90anti-evil-maid/anti-evil-maid-unseal
@@ -24,6 +24,7 @@ plymouth_message() {
         PLYMOUTH_MESSAGES+=("$*")
 }
 . antievilmaid_boilerplate
+alias unsealed="[  ! -e $SRK_PASSWORD_CACHE ]"
 
 
 # mount the AEM device
@@ -92,19 +93,18 @@ else
     SEALED_SECRET=$sealed_secret_txt
 fi
 
-if [ -f "$SEALED_SECRET" ] ; then
-    Z=$(tpm_z_srk)
+Z=$(tpm_z_srk)
 
-    message "Attempting to unseal the secret from the TPM..."
+message "Attempting to unseal the secret from the TPM..."
 
-    # we try only once as some TCG 1.2 TPMs start "protecting themselves against
-    # dictionary attacks" when there's more than 1 try within a short time... -_-
-    # (TCG 2 fixes that):
-    ${Z:+:} systemd-ask-password "Enter TPM SRK password" |
-    tpm_unsealdata $Z -i "$SEALED_SECRET" -o "$UNSEALED_SECRET"
-else
-    message "No data to unseal. Don't forget to generate a ${SEALED_SECRET##*/}"
-fi
+# we try only once as some TCG 1.2 TPMs start "protecting themselves against
+# dictionary attacks" when there's more than 1 try within a short time... -_-
+# (TCG 2 fixes that). TODO: just reset this "protection" with tpm_resetdalock
+
+${Z:+:} systemd-ask-password "Enter TPM SRK password" |
+tee "$SRK_PASSWORD_CACHE" |
+tpm_unsealdata $Z -i "$SEALED_SECRET" -o "$UNSEALED_SECRET" &&
+rm "$SRK_PASSWORD_CACHE"
 
 log "Unmounting the $LABEL device..."
 umount "$MNT"
@@ -112,43 +112,48 @@ umount "$MNT"
 
 # display the secret in the next (.png) or the current dialog (.txt)
 
-if png; then
-    # Verify if the unsealed PNG secret seems valid and replace the lock icon
-    if file "$UNSEALED_SECRET" 2>/dev/null | grep -q PNG; then
-        cp "$UNSEALED_SECRET" "$PLYMOUTH_THEME_UNSEALED_SECRET"
+if unsealed; then
+    if png; then
+        # Verify if the unsealed PNG secret seems valid and replace the lock icon
+        if file "$UNSEALED_SECRET" 2>/dev/null | grep -q PNG; then
+            cp "$UNSEALED_SECRET" "$PLYMOUTH_THEME_UNSEALED_SECRET"
+        fi
+
+        WHERE="next to the prompt for it"
+    else
+        {
+            message ""
+            message "$(cat "$UNSEALED_SECRET" 2>/dev/null)"
+            message ""
+        } 2>&1  # don't put the secret into the journal
+
+        WHERE="above"
     fi
-
-    WHERE="next to the prompt for it"
-else
-    {
-        message ""
-        message "$(cat "$UNSEALED_SECRET" 2>/dev/null)"
-        message ""
-    } 2>&1  # don't put the secret into the journal
-
-    WHERE="above"
-fi
-message "Never type in your disk password unless the secret $WHERE is correct!"
+    message "Never type in your disk password unless the secret $WHERE is correct!"
 
 
-# pause
+    # pause
 
-if removable; then
-    waitfor ! -b "$DEV"
-else
-    if ! png; then
-        msg="Press <ENTER> to continue..."
-        if plymouth_active; then
-            message "$msg"
-            plymouth watch-keystroke --keys=$'\n'
-        else
-            systemd-ask-password "$msg" >/dev/null
+    if removable; then
+        waitfor ! -b "$DEV"
+    else
+        if ! png; then
+            msg="Press <ENTER> to continue..."
+            if plymouth_active; then
+                message "$msg"
+                plymouth watch-keystroke --keys=$'\n'
+            else
+                systemd-ask-password "$msg" >/dev/null
+            fi
         fi
     fi
 fi
 
 
-# hide the secret
+# Clear all messages to hide the secret. Do it even if the unsealing has failed,
+# because that's how an attacker would likely behave to trick absentminded users
+# into thinking that they've already seen the secret. (See AEM introductory blog
+# post FAQ, "Why are there no negative indicators")
 
 if removable || ! png; then
     if plymouth_active; then
