add multi-factor AEM support

diff --git a/anti-evil-maid/90anti-evil-maid/anti-evil-maid-unseal b/anti-evil-maid/90anti-evil-maid/anti-evil-maid-unseal
--- a/anti-evil-maid/90anti-evil-maid/anti-evil-maid-unseal
+++ b/anti-evil-maid/90anti-evil-maid/anti-evil-maid-unseal
@@ -69,22 +69,23 @@ log "Mounting the ${LABEL:?} device..."
 mkdir -p "$MNT"
 mount -t ext4 -o ro "$DEV" "$MNT"
 
-if external "$DEV" && removable "$DEV"; then
-    alias remove=true
-else
-    alias remove=false
-fi
 
-
-# setup TPM
+# setup TPM & copy secrets to tmp
 
 log "Initializing TPM..."
 modprobe tpm_tis
 ip link set dev lo up
 mkdir -p "${TPMS_DIR%/*}"
+log "Copying sealed AEM secrets..."
 cp -Tr "$MNT/aem/${TPMS_DIR##*/}" "${TPMS_DIR}"
 tcsd_changer_identify
 tcsd
+
+
+# unmount AEM device
+
+log "Unmounting the $LABEL device..."
+umount "$MNT"
 
 
 # Extend PCR with LUKS header(s)
@@ -103,21 +104,19 @@ while read luksid; do
 done
 
 
-# unseal the secret and unmount the AEM device
+# set up caches
 
 sealed_secret_txt=$TPM_DIR/$LABEL/secret.txt.sealed2
 sealed_secret_png=$TPM_DIR/$LABEL/secret.png.sealed2
-
-if plymouth_active && [ -e "$sealed_secret_png" ]; then
-    alias png=true
-    SEALED_SECRET=$sealed_secret_png
-else
-    alias png=false
-    SEALED_SECRET=$sealed_secret_txt
-fi
+sealed_secret_key=$TPM_DIR/$LABEL/secret.key.sealed2
+sealed_secret_otp=$TPM_DIR/$LABEL/secret.otp.sealed2
+sealed_secret_fsh=$TPM_DIR/$LABEL/secret.fsh.sealed2
 
 mkdir -p "$CACHE_DIR"
 echo "${LABEL##$LABEL_PREFIX}" >"$SUFFIX_CACHE"
+
+
+# cache SRK password, if applicable
 
 Z=$(tpm_z_srk)
 
@@ -134,46 +133,173 @@ else
              break
         fi
 
-        log "Wrong SRK password, resetting dictionary attack lock..."
-        tpm_resetdalock -z || true  # -z is an empty owner (not SRK) password
+        log "Wrong SRK password"
     done
 fi
 
-log "Unsealing the secret..."
-if tpm_unsealdata $Z -i "$SEALED_SECRET" -o "$UNSEALED_SECRET" \
-   <"$SRK_PASSWORD_CACHE"; then
-    rm -rf "$CACHE_DIR"
+
+# check freshness token
+
+log "Unsealing freshness token..."
+if tpm_unsealdata $Z -i "$sealed_secret_fsh" -o /tmp/fresh \
+        < "$SRK_PASSWORD_CACHE"; then
+    log "Freshness token unsealed."
+else
+    log "Freshness token unsealing failed!"
+    exit 1
 fi
 
-log "Unmounting the $LABEL device..."
-umount "$MNT"
+if checkfreshness /tmp/fresh; then
+    log "Freshness token valid, continuing."
+else
+    log "Freshness token invalid!"
+    exit 1
+fi
+
+rm -f /tmp/fresh
 
 
-if [ ! -d "$CACHE_DIR" ]; then  # unseal succeeded
-    if png; then
-        # display secret in next dialog
-        WHERE="next to the prompt for it"
-        if file "$UNSEALED_SECRET" 2>/dev/null | grep -q PNG; then
-            cp "$UNSEALED_SECRET" "$PLYMOUTH_THEME_UNSEALED_SECRET"
-        fi
-    else
-        # display secret in current dialog
-        WHERE="above"
-        {
-            message ""
-            message "$(cat "$UNSEALED_SECRET" 2>/dev/null)"
-            message ""
-        } 2>&1  # don't put the secret into the journal
+# OTP sanity check
+
+if [ -e "$sealed_secret_otp" ]; then
+    if ! external "$DEV" || ! removable "$DEV"; then
+        # evil maid can gain access to OTP secret, don't trust it
+        message "Multi-factor AEM device not external/removable, aborting!"
+        exit 1
     fi
-    message "Never type in your disk password unless the secret $WHERE is correct!"
+
+    alias otp=true
+    SEALED_SECRET=$sealed_secret_otp
+else
+    alias otp=false
+fi
 
 
-    # pause
+# tell user to remove AEM dev if RO
 
-    if remove; then
-        waitfor ! -b "$DEV"
+message ""
+message "You should now unplug the AEM device if it's read-only."
+message ""
+
+
+# unseal & show OTP if provisioned
+
+if otp; then
+    log "Unsealing TOTP shared secret seed..."
+    if tpm_unsealdata $Z -i "$SEALED_SECRET" -o "$UNSEALED_SECRET" \
+            < "$SRK_PASSWORD_CACHE"; then
+        log "TOTP secret unsealed."
+        seed=$(cat "$UNSEALED_SECRET")
+
+        message "Please verify your OTP device displays the same TOTP code"
+        message "as shown below. Should the codes match, press <ENTER> to"
+        message "unseal your LUKS key file. If you do now have access to"
+        message "your OTP device but wish to continue despite the security"
+        message "implications, press <ENTER>. Pressing <Q> will revert"
+        message "back to displaying PNG/TXT secret (if provisioned)."
+        message "Otherwise, shut down the computer."
+        message ""
+        message "[ $(date) ] TOTP code: $(oathtool --totp -b "$seed")"
+        last=$(date +%s)
+
+        if plymouth_active; then
+            plymouth watch-keystroke --keys=$'\n' --command='touch /tmp/mfa-cont' &
+            plymouth watch-keystroke --keys=Qq --command='touch /tmp/mfa-skip' &
+            while [ ! -e /tmp/mfa-cont ] && [ ! -e /tmp/mfa-skip ]; do
+                now=$(date +%s)
+                if [ "$((now % 30))" -eq 0 ] && [ ! "$last" == "$now" ]; then
+                    message "[ $(date) ] TOTP code: $(oathtool --totp -b "$seed")"
+                    last=$now
+                else
+                    sleep 0.1
+                fi
+            done
+
+            if [ -e /tmp/mfa-skip ]; then
+                alias otp=false
+                message "Reverting back to non-multi-factor AEM boot"
+            fi
+        else
+            tout=$((30 - ($(date +%s) % 30)))
+            while true; do
+                if systemd-ask-password --echo --timeout "$tout" \
+                        "Press <ENTER> to continue or <Q> + <ENTER> to skip multi-factor AEM." \
+                        >/tmp/mfa-resp; then
+                    if grep -qi q /tmp/mfa-resp; then
+                        alias otp=false
+                        message "Reverting back to non-multi-factor AEM boot"
+                    fi
+                    break
+                fi
+
+                message "[ $(date) ] TOTP code: $(oathtool --totp -b "$seed")"
+                tout=30
+            done
+        fi
+
+        rm -f "$UNSEALED_SECRET"
     else
-        if ! png; then
+        # unsealing OTP seed failed, don't even search for keyfile
+        alias otp=false
+    fi
+fi
+
+
+# determine which secret to use next
+
+alias png=false
+if otp; then
+    # user does not want to skip multi-factor AEM
+    SEALED_SECRET=$sealed_secret_key
+    # not checking key file existence since we DO NOT want
+    # the static secrets to be displayed anyway
+elif plymouth_active && [ -e "$sealed_secret_png" ]; then
+    alias png=true
+    SEALED_SECRET=$sealed_secret_png
+else
+    SEALED_SECRET=$sealed_secret_txt
+fi
+
+
+# unseal the next secret
+
+log "Unsealing the secret $SEALED_SECRET..."
+if tpm_unsealdata $Z -i "$SEALED_SECRET" -o "$UNSEALED_SECRET" \
+        <"$SRK_PASSWORD_CACHE"; then
+    if otp; then
+        # ask for LUKS key file passphrase
+        for try in 1 2 3; do
+            if systemd-ask-password "LUKS key file password" |
+                    scrypt dec -P "$UNSEALED_SECRET" /tmp/aem-keyfile; then
+                log "Correct LUKS key file password"
+                message "Key file decrypted."
+                # decrypted key file saved in /tmp/aem-keyfile;
+                # dracut "90crypt" module will parse the
+                #   rd.luks.key=/tmp/aem-keyfile
+                # kernel cmdline arg and attempt to use it;
+                # this file is deleted on root switch
+                # along with everything in /tmp
+                break
+            else
+                log "Wrong LUKS key file password"
+            fi
+        done
+    else
+        if png; then
+            # display secret in next dialog
+            message "Never type in your disk password unless the secret next to the prompt for it is correct!"
+            if file "$UNSEALED_SECRET" 2>/dev/null | grep -q PNG; then
+                cp "$UNSEALED_SECRET" "$PLYMOUTH_THEME_UNSEALED_SECRET"
+            fi
+        else
+            # display secret in current dialog
+            {
+                message ""
+                message "$(cat "$UNSEALED_SECRET" 2>/dev/null)"
+                message ""
+            } 2>&1  # don't put the secret into the journal
+            message "Never type in your disk password unless the secret above is correct!"
+
             msg="Press <ENTER> to continue..."
             if plymouth_active; then
                 message "$msg"
@@ -186,12 +312,16 @@ if [ ! -d "$CACHE_DIR" ]; then  # unseal succeeded
 fi
 
 
+rm -f "$UNSEALED_SECRET"
+
+
 # Clear all messages to hide the secret. Do it even if the unsealing has failed,
 # because that's how an attacker would likely behave to trick absentminded users
 # into thinking that they've already seen the secret. (See AEM introductory blog
 # post FAQ, "Why are there no negative indicators")
 
-if remove || ! png; then
+# hiding msg for png secret would delete the password prompt warning
+if ! png; then
     if plymouth_active; then
         for m in "${PLYMOUTH_MESSAGES[@]}"; do
             plymouth hide-message --text="$m"
@@ -201,4 +331,10 @@ if remove || ! png; then
     clear
 fi
 
-rm -f "$UNSEALED_SECRET"
+
+# prevent sealing service from starting if user unplugged
+# the (supposedly read-only) AEM device
+
+if [ ! -b "$DEV" ]; then
+    rm -rf "$CACHE_DIR"
+fi
diff --git a/anti-evil-maid/sbin/anti-evil-maid-install b/anti-evil-maid/sbin/anti-evil-maid-install
--- a/anti-evil-maid/sbin/anti-evil-maid-install
+++ b/anti-evil-maid/sbin/anti-evil-maid-install
@@ -11,7 +11,7 @@ usage() {
     cat <<END
 
 Usage:
-  anti-evil-maid-install [-s <suffix>] [-F] <device>
+  anti-evil-maid-install [-s <suffix>] [-F] [-m] <device>
 
   Installs Anti Evil Maid to your system's boot partition, or to a different
   storage device (e.g. an SD card or a USB stick).
@@ -30,6 +30,10 @@ Arguments:
 
   -F: passed on to mkfs.ext4 (don't ask for confirmation, etc.)
 
+  -m: set up a multi-factor auth AEM media (EXPERIMENTAL)
+      Using time-based one time password and a LUKS key file, provides resistance
+      to shoulder surfing and video surveillance based passphrase snooping.
+
 
 Examples:
   Install on the system's boot partition (assuming that it is /dev/sda1), and
@@ -42,6 +46,11 @@ Examples:
 
     anti-evil-maid-install -s .sd /dev/mmcblk0p1
 
+  Install MFA-enabled AEM on USB stick's first partition, overwriting it with
+  a new ext4 filesystem and marking it bootable:
+
+    anti-evil-maid-install -m /dev/sdb1
+
 END
 
     exit 1
@@ -50,11 +59,13 @@ END
 
 # check invocation
 
+alias mfa=false
 unset LABEL_SUFFIX F
-while getopts s:Fh opt; do
+while getopts s:Fhm opt; do
     case "$opt" in
         s) LABEL_SUFFIX=$OPTARG ;;
         F) F=-F ;;
+        m) alias mfa=true; systemctl start tcsd ;;
         *) usage ;;
     esac
 done
@@ -76,6 +87,11 @@ fi
 if [ -z "$(getluksuuids)" ]; then
     log "Anti Evil Maid requires encrypted disk!"
     exit 1
+fi
+
+if ! tpm_id >/dev/null; then
+    log "Creating a TPM ID (you will be prompted for owner pw)."
+    tpm_id -c
 fi
 
 
@@ -100,6 +116,19 @@ PART_DEV_REAL=$(readlink -f "$PART_DEV")
 PART_NUM=${PART_DEV_REAL##*[!0-9]}
 if ! [ "$PART_NUM" -gt 0 ]; then
     log "Couldn't extract partition number: $PART_NUM"
+    exit 1
+fi
+
+
+# MFA-specific checks
+
+if mfa && ! external "$PART_DEV"; then
+    log "MFA-enabled AEM cannot be installed on the same storage device as Qubes OS."
+    exit 1
+elif mfa && ! removable "$PART_DEV" "$LABEL" ; then
+    log "MFA-enabled AEM can only be used with removable media."
+    log "Should the device be, in fact, removable (autodetection failed),"
+    log "add '.rm=1' at the end of disk label suffix using the '-s' option."
     exit 1
 fi
 
@@ -142,6 +171,147 @@ if [   -n "$OLD_LABEL" -a \
        -e "$AEM_DIR/$OLD_LABEL" -a \
      ! -e "$AEM_DIR/$LABEL" ]; then
     mv -v "$AEM_DIR/$OLD_LABEL" "$AEM_DIR/$LABEL"
+fi
+
+
+# MFA: generate a TOTP seed
+
+if mfa && [ ! -e "$AEM_DIR/$LABEL/secret.otp" ]; then
+    log "Generating new 160-bit TOTP seed"
+    mkdir -p "$AEM_DIR/$LABEL"
+    head -c 20 /dev/random \
+        | base32 -w 0 \
+        | tr -d '=' \
+        > "$AEM_DIR/$LABEL/secret.otp"
+
+    # construct OTP URI
+    otp_label="Qubes%20OS%3A%20Anti%20Evil%20Maid"
+    otp_secret="$(cat "$AEM_DIR/$LABEL/secret.otp")"
+    otp_uri="otpauth://totp/${otp_label}?secret=${otp_secret}"
+
+    # create an ANSI text QR code and show it in the terminal
+    echo "$otp_uri" | qrencode -t ansiutf8
+
+    # show QR code
+    log "Please scan the above QR code with your OTP device."
+
+    # display the text form of secret to user, too
+    human_readable_secret="$(echo "$otp_secret" | sed 's/\(....\)/\1\ /g')"
+    log "Alternatively, you may manually enter the following secret into"
+    log "your OTP device:"
+    log "    $human_readable_secret"
+
+    if timedatectl status | grep -q 'RTC in local TZ: yes'; then
+        log ""
+        log "WARNING: Your computer's RTC (real-time clock) is set to"
+        log "store time in local timezone. This will cause wrong TOTP"
+        log "codes to be generated during AEM boot. Please fix this by"
+        log "running (as root):"
+        log "    timedatectl set-local-rtc 0"
+    fi
+
+    # check whether secret was provisioned correctly
+    log ""
+    log "After you have set up your OTP device, please enter the code"
+    log "displayed on your device and press <ENTER> to continue."
+    log ""
+
+    totp_tries=3
+    for try in $(seq $totp_tries); do
+        read -p "Code: "
+        if ! oathtool --totp -b "$otp_secret" "$REPLY" >/dev/null; then
+            log "Entered TOTP code is invalid!"
+            if [ "$try" -lt $totp_tries ]; then
+                log "Please check clock synchronization."
+                log "If you made a mistake while manually entering the secret,"
+                log "remove the added token, repeat the process and try again."
+                log ""
+            else
+                log "Aborting AEM setup..."
+                exit 1
+            fi
+        else
+            break
+        fi
+    done
+
+    log "TOTP code matches, continuing AEM setup."
+fi
+
+
+# MFA: generate and enroll a LUKS key file if not already present
+
+if mfa && [ ! -e "$AEM_DIR/$LABEL/secret.key" ]; then
+    log "Generating new LUKS key file"
+    rawkey=$(mktemp)
+    head -c 64 /dev/random > "$rawkey"
+
+    log "Encrypting key file"
+    mkdir -p "$AEM_DIR/$LABEL"
+    scrypt enc "$rawkey" "$AEM_DIR/$LABEL/secret.key"
+
+    for dev in $(getluksuuids); do
+        devname=$(readlink -f "/dev/disk/by-uuid/$dev")
+
+        # check if LUKS device has any free key slots
+        # FIXME: possibility of failing due to i18n?
+        if ! cryptsetup luksDump "/dev/disk/by-uuid/$dev" \
+                | grep -q DISABLED; then
+            log "FATAL: Device $devname (UUID $dev) has no free key slots!"
+            exit 1
+        fi
+
+        log "Adding key file to new key slot for $devname (UUID $dev)"
+        for try in 1 2 3; do
+            if cryptsetup luksAddKey "/dev/disk/by-uuid/$dev" "$rawkey"; then
+                break
+            elif [ $try -eq 3 ]; then
+                log "ERROR: Wrong password, aborting!"
+                log "You need to manually finish enrolling $rawkey"
+                log "as a key file for all desired LUKS devices, then"
+                log "remove the $rawkey file and re-run this script."
+                exit 1
+            fi
+        done
+    done
+
+    log "Shredding the unencrypted key file"
+    shred -zu "$rawkey"
+fi
+
+
+# define a TPM NVRAM area for storing freshness token hashes
+
+if ! checktpmnvram; then
+    log "Creating TPM NVRAM area for freshness tokens (prompts for TPM owner password)"
+    for try in 1 2 3; do
+        if createtpmnvram; then
+            break
+        elif [ $try -eq 3 ]; then
+            log "Too many failures, aborting!"
+            exit 1
+        fi
+    done
+fi
+
+
+# add the AEM media being created to the freshness database
+
+if suffixtoslot "$LABEL_SUFFIX"; then
+    log "WARNING: (possibly another) AEM media with the same label"
+    log "suffix is already enrolled in the freshness token database!"
+    log "Overwriting will result in the old AEM media failing to"
+    log "perform a successful AEM boot. If you're simply reinstalling"
+    log "on the same device or intentionally replacing an old AEM media"
+    log "that was lost/destroyed/etc., it is safe to continue."
+    read -p "Proceed? [y/N] " response
+    case "$response" in
+        y|Y) echo "continuing..." ;;
+        *) exit ;;
+    esac
+else
+    assignslottosuffix "$LABEL_SUFFIX"
+    log "Assigned slot $(suffixtoslot "$LABEL_SUFFIX") to this AEM media"
 fi
 
 
diff --git a/anti-evil-maid/sbin/anti-evil-maid-lib b/anti-evil-maid/sbin/anti-evil-maid-lib
--- a/anti-evil-maid/sbin/anti-evil-maid-lib
+++ b/anti-evil-maid/sbin/anti-evil-maid-lib
@@ -5,6 +5,10 @@ TPMS_DIR=${TPM_DIR}s
 CACHE_DIR=/run/anti-evil-maid
 SRK_PASSWORD_CACHE=$CACHE_DIR/srk-password
 SUFFIX_CACHE=$CACHE_DIR/suffix
+TPM_FRESHNESS_PASSWORD=$AEM_DIR/tpm-freshness-pw
+TPM_FRESHNESS_INDEX="0x41454d"
+TPM_FRESHNESS_DB=$AEM_DIR/tpm-freshness-db
+TPM_FRESHNESS_SLOTS=8
 
 
 # work with or without plymouth
@@ -54,6 +58,169 @@ waitfor() {
     message "$_file $_what"
 }
 
+checktpmnvram() {
+    # checks whether the TPM NVRAM area is defined
+    # NOTE: tpm_nvinfo does not return non-zero if requested index
+    # is not a defined NVRAM area so we need to parse
+    if ! tpm_nvinfo -i "$TPM_FRESHNESS_INDEX" | grep -q 'AUTHWRITE'; then
+        return 1
+    fi
+}
+
+createtpmnvram() {
+    # create the world-readable/AUTHWRITE TPM NVRAM area to hold up to
+    # TPM_FRESHNESS_SLOTS anti-replay freshness token hashes
+    # NOTE: interactively asks for owner password (accepts password from
+    # stdin only if process has no controlling TTY)
+    if [ ! -e "$TPM_FRESHNESS_PASSWORD" ]; then
+        message "Generating TPM NVRAM area AUTHWRITE password"
+        head -c 16 /dev/random | od -A n -v -t x1 \
+            | tr -d ' \n' > "$TPM_FRESHNESS_PASSWORD"
+    fi
+
+    _pw=$(cat "$TPM_FRESHNESS_PASSWORD")
+
+    if ! tpm_nvdefine -i "$TPM_FRESHNESS_INDEX" \
+	    -s $((TPM_FRESHNESS_SLOTS * 20)) \
+            -p AUTHWRITE --pwda="$_pw" --pwdo; then
+        return 1
+    fi
+}
+
+suffixtoslot() {
+    # consults the $TPM_FRESHNESS_DB file and returns the
+    # slot number assigned to the AEM media given its label suffix
+    # as the first argument
+    if [ ! -e "$TPM_FRESHNESS_DB" ]; then
+        message "'$TPM_FRESHNESS_DB' does not exist, aborting!"
+        return 1
+    fi
+
+    if _slot=$(grep ":$1\$" "$TPM_FRESHNESS_DB"); then
+        echo "$_slot" | cut -d ':' -f 1 | head -n 1
+    else
+        return 1
+    fi
+}
+
+assignslottosuffix() {
+    # assigns an unused freshness slot number (if available) to an AEM
+    # media identified by its label suffix (optionally passed as the first
+    # argument
+    if [ ! -e "$TPM_FRESHNESS_DB" ]; then
+        touch "$TPM_FRESHNESS_DB"
+    fi
+
+    _suff=${1-$(cat "$SUFFIX_CACHE")}
+    if grep -q "$_suff" "$TPM_FRESHNESS_DB"; then
+        message "AEM device suffix '$_suff' already in DB!"
+        return 1
+    fi
+
+    _enrolled=$(wc -l < "$TPM_FRESHNESS_DB")
+    if [ "$_enrolled" -ge $TPM_FRESHNESS_SLOTS ]; then
+        message "No more freshness token slots available!"
+        return 1
+    fi
+
+    echo "$_enrolled:$_suff" >> "$TPM_FRESHNESS_DB"
+    echo "$_enrolled"
+}
+
+checkfreshness() {
+    # check whether hash of an usealed freshness token (file path
+    # given as an argument) is contained in TPM NVRAM area
+    # NOTE: tpm_nvread prints info msg to stdout for some reason,
+    # so we write the raw bytes to stderr and redirect stdout
+    # to /dev/null while stderr is redirected to stdout
+    # (the order here matters! "2>&1" needs to come *before*
+    # "1>/dev/null" to achieve desired result)
+    _hash=$(sha1sum "$1" | cut -d ' ' -f 1)
+    _lastslot=$((TPM_FRESHNESS_SLOTS - 1))
+    for _i in $(seq 0 $_lastslot); do
+        _slot=$(tpm_nvread -i "$TPM_FRESHNESS_INDEX" \
+            -n "$((_i * 20))" -s 20 \
+            -f /dev/stderr 2>&1 1>/dev/null \
+	    | od -A n -v -t x1 | tr -d ' \n')
+        if [ "$_hash" == "$_slot" ]; then
+            message "Matching freshness token hash found in slot #$_i"
+            return 0
+        fi
+    done
+    message "Freshness token does not match any slot in TPM NVRAM!"
+    return 1
+}
+
+updatefreshness() {
+    # takes a path to the new freshness token as an argument and
+    # stores its sha1 hash in the appropriate freshness token slot
+    # of the TPM NVRAM area; optional second argument is the AEM
+    # boot device label suffix
+    if [ ! -e "$TPM_FRESHNESS_PASSWORD" ]; then
+        message "TPM NVRAM area AUTHWRITE password file does not exist!"
+        return 1
+    fi
+
+    _suff=${2-$(cat "$SUFFIX_CACHE")}
+    if ! _slot=$(suffixtoslot "$_suff"); then
+        message "Suffix '$_suff' not in DB, attempting to create..."
+        if ! _slot=$(assignslottosuffix "$_suff"); then
+            message "Failed to add suffix '$_suff' into DB!"
+            return 1
+        fi
+    fi
+
+    _pw=$(cat "$TPM_FRESHNESS_PASSWORD")
+    _tmpf=$(mktemp)
+    sha1sum "$1" | cut -d ' ' -f 1 | xxd -r -ps > "$_tmpf"
+    if tpm_nvwrite -i "$TPM_FRESHNESS_INDEX" \
+	    -n "$((_slot * 20))" -s 20 \
+            --password="$_pw" -f "$_tmpf"; then
+        _ret=0
+    else
+        _ret=1
+    fi
+    rm -f "$_tmpf"
+    return $_ret
+}
+
+revokefreshness() {
+    # invalidates the freshness token of a specified AEM media (by its
+    # label suffix
+    if _slot=$(suffixtoslot "$1"); then
+        message "Invalidating freshness token for AEM device with suffix '$_suff'..."
+        _pw=$(cat "$TPM_FRESHNESS_PASSWORD")
+        if tpm_nvwrite -i "$TPM_FRESHNESS_INDEX" \
+                -n "$((_slot * 20))" -s 20 \
+                --password="$_pw" -m "0xff"; then
+            message "Done."
+        else
+            message "Failed!"
+        fi
+    else
+        message "AEM device with label suffix '$_suff' not found in DB!"
+    fi
+}
+
+resetfreshness() {
+    # invalidates ALL freshness tokens
+    message "Invalidating **ALL** freshness tokens..."
+    _pw=$(cat "$TPM_FRESHNESS_PASSWORD")
+    if tpm_nvwrite -i "$TPM_FRESHNESS_INDEX" \
+            -s "$((TPM_FRESHNESS_SLOTS * 20))" \
+            --password="$_pw" -m "0xff"; then
+        message "Done."
+    else
+        message "Failed!"
+    fi
+}
+
+destroytpmnvram() {
+    # releases the TPM NVRAM area
+    # NOTE: requires owner password to be entered interactively
+    tpm_nvrelease -i "$TPM_FRESHNESS_INDEX" --pwdo
+}
+
 synctpms() {
     _label=${1:?}
     _mnt=${2:?}
@@ -96,11 +263,16 @@ external() {
 }
 
 removable() {
-    _rm=$(lsblk -dnr -o RM,LABEL "$1")
+    _rm="$(lsblk -dnr -o RM "$1") ${2-$(lsblk -dnr -o LABEL "$1")}"
     case "$_rm" in
         *.rm=[01]) _rm=${_rm##*=} ;;
                 *) _rm=${_rm%% *} ;;
     esac
 
     [ "$_rm" = 1 ]
+}
+
+writable() {
+    _ro=$(lsblk -dnr -o RO "$1")
+    [ "$_ro" = 0 ]
 }
diff --git a/anti-evil-maid/sbin/anti-evil-maid-seal b/anti-evil-maid/sbin/anti-evil-maid-seal
--- a/anti-evil-maid/sbin/anti-evil-maid-seal
+++ b/anti-evil-maid/sbin/anti-evil-maid-seal
@@ -15,10 +15,29 @@ source anti-evil-maid-lib
 trap 'rm -rf "$CACHE_DIR"' EXIT
 
 
+# scream loudly if sealing fails for some reason
+# (eg. AEM media read-only)
+_failure() {
+    message "Failed to seal secrets (error @ line $1)!"
+
+    msg="Press <ENTER> to continue..."
+    if plymouth_active; then
+        message "$msg"
+        plymouth watch-keystroke --keys=$'\n'
+    else
+        systemd-ask-password "$msg" >/dev/null
+    fi
+
+    exit 1
+}
+trap '_failure $LINENO' ERR
+
+
 # define sealing and device variables
 
 source /etc/anti-evil-maid.conf
 Z=$(tpm_z_srk)
+
 
 LABEL=$LABEL_PREFIX${1-$(cat "$SUFFIX_CACHE")}
 DEV=/dev/disk/by-label/$LABEL
@@ -36,12 +55,18 @@ if grep -E "^PCR-(${pcrs//$'\n'/|}):( 00| FF){20}" /sys/devices/*/*/pcrs;
 fi
 
 
+# regenerate the freshness token and store it's hash in TPM
+
+head -c 20 /dev/random > "$AEM_DIR/$LABEL/secret.fsh"
+updatefreshness "$AEM_DIR/$LABEL/secret.fsh" "${1-$(cat "$SUFFIX_CACHE")}"
+
+
 # seal and save secret(s) to root partition
 
 mkdir -p "$TPM_DIR/$LABEL"
 
 SEALED=0
-for ext in txt png; do
+for ext in txt png key otp fsh; do
      input=$AEM_DIR/$LABEL/secret.$ext
     output=$TPM_DIR/$LABEL/secret.$ext.sealed2
 
@@ -50,7 +75,7 @@ for ext in txt png; do
     elif if [ ! -t 0 ]; then cat "$SRK_PASSWORD_CACHE"; fi |
          tpm_sealdata $Z $SEAL -i "$input" -o "$output"; then
         rm -f "${output%2}"
-        SEALED=$(($SEALED + 1))
+        SEALED=$((SEALED + 1))
         message "Sealed $input using $SEAL"
     else
         message "Failed $input"
