(3/3) Do the right thing when installing to the internal boot partition

diff --git a/antievilmaid_install b/antievilmaid_install
--- a/antievilmaid_install
+++ b/antievilmaid_install
@@ -58,6 +58,7 @@ else
 fi
 echo "--> Looks like you're installing to $TYPE"
 
+if external; then
     TMP_DIR=`mktemp -d /tmp/antievilmaid-XXXXXXX`
 
     echo "About to format device: $TARGET_PART..."
@@ -71,28 +72,37 @@ echo "--> Looks like you're installing to $TYPE"
 
     echo "--> Formatting as ext4..."
     mkfs.ext4 -q $TARGET_PART
+fi
 
 echo "--> Labeling as '$BOOTLABEL'..."
-e2label $TARGET_PART $BOOTLABEL
+e2label $TARGET_PART $BOOTLABEL || exit 1  # FIXME: fails on btrfs boot partitions
 
+if external; then
     echo "--> Mounting new boot partition..."
     MNT=$TMP_DIR/mnt
     mkdir $MNT
     mount $TARGET_PART $MNT || exit 1
+else
+    MNT=$CURRENT_BOOT_PART
+fi
 
 
 unmount_and_die () {
+    if external; then
         umount $MNT && rm -fr $MNT || exit 1
         rm -fr $TMP_DIR
+    fi
     exit 1
 }
 
+if external; then
     echo "--> Copying your boot images..."
     for f in $CURRENT_BOOT_PART/* ; do
         [ -d $f ] && continue
         echo "Copying $f"
         cp $f $MNT/ || unmount_and_die
     done
+fi
 
 echo "--> Rebuilding initramfs modules"
 for initramfs in $MNT/initramfs-*.img ; do
@@ -102,12 +112,14 @@ for initramfs in $MNT/initramfs-*.img ; do
     dracut --force $MNT/$initramfs $kernelver
 done
 
+if external; then
     echo "--> Copying grub themes..."
     mkdir -p $MNT/grub2/themes/
     for d in $CURRENT_BOOT_PART/grub2/themes/* ; do
         echo "Copying theme "`basename $d`
         cp -r $d $MNT/grub2/themes/
     done
+fi
 
 echo "--> Copying TPM files..."
 mkdir $MNT/antievilmaid/
@@ -119,6 +131,7 @@ if ! [ -f /var/lib/tpm/system.data ] ; then
 fi
 cp /var/lib/tpm/system.data $MNT/antievilmaid/ || unmount_and_die
 
+if external; then
     echo "--> Installing GRUB2 on the target device..."
     grub2-install --boot-directory=$MNT $TARGET_DEV
 
@@ -128,6 +141,7 @@ cp /var/lib/tpm/system.data $MNT/antievilmaid/ || unmount_and_die
     echo "--> Switching boot partition to antievilmaid..."
     umount $CURRENT_BOOT_PART
     mount $TARGET_PART $CURRENT_BOOT_PART
+fi
 
 echo "--> Disabling vanilla generation of tboot entries polluting the grub configuration"
 chmod -x /etc/grub.d/20_linux_tboot
@@ -136,6 +150,7 @@ chmod -x /etc/grub.d/20_linux_xen_tboot
 echo "--> Generating grub configuration..."
 grub2-mkconfig -o $CURRENT_BOOT_PART/grub2/grub.cfg
 
+if external; then
     echo "--> Reswitching boot partition..."
     umount $CURRENT_BOOT_PART
     mount $CURRENT_BOOT_PART
@@ -148,3 +163,4 @@ grub2-mkconfig -o $CURRENT_BOOT_PART/grub2/grub.cfg
     #EOF
     #
     rm -fr $TMP_DIR || exit 1
+fi
