(1/3) Do the right thing when installing to the internal boot partition
This commit only adds the code to detect internal/external installation
mode, but does not use it yet.

diff --git a/antievilmaid_install b/antievilmaid_install
--- a/antievilmaid_install
+++ b/antievilmaid_install
@@ -47,6 +47,17 @@ if ! [ -b $TARGET_PART ] ; then
     exit 1
 fi
 
+devmm=`mountpoint --devno    "$TARGET_PART"`       || exit 1
+dirmm=`mountpoint --fs-devno "$CURRENT_BOOT_PART"` || exit 1
+if [ "$devmm" = "$dirmm" ]; then  # FIXME: fails on btrfs boot partitions
+    alias external=false
+    TYPE="the internal boot partition"
+else
+    alias external=true
+    TYPE="an external device"
+fi
+echo "--> Looks like you're installing to $TYPE"
+
 TMP_DIR=`mktemp -d /tmp/antievilmaid-XXXXXXX`
 
 echo "About to format device: $TARGET_PART..."
